Metrics/LineLength:
  Description: Limit lines to 120 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 120
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Metrics/CyclomaticComplexity:
  Description: A complexity metric that is strongly correlated to the number of test
    cases needed to validate a method.
  Enabled: true
  Max: 10
Metrics/MethodLength:
  Description: Avoid methods longer than 22 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: true
  CountComments: true
  Max: 22
Style/ClassVars:
  Enabled: false